### ISSUE TITLE
Add shortcuts for chat commands: .c, .tc, .pc

### ISSUE THREAD

**Issue by PatPeter** [EliteSCP/TextChat#2]
It would be easier to get people to use this plugin universally if the command to use the chat were shorter, in the realm of 1 or 2 characters:

```
.chat public -> .c
.chat team -> .tc
.chat private -> .pc
```

Public chat should be the default and the shortest acronym.

**Comment by iopietro** [comment]
Similar shortcuts already exist:
```
.chat public -> .c p
.chat team -> .c t
.chat private -> .c pr
```

**Comment by PatPeter** [comment]
The problem is that most of SCP:SL's population are children and having to explain to them it's "Press ~ and type period c SPACE p NOT cp" is an uphill battle.

**Comment by iopietro** [comment]
Won't be done for now.
